name: bootcamp_challenge2
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.17.3 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    bloc_concurrency: ^0.2.0
    copy_with_extension: ^4.0.0
    cupertino_icons: ^1.0.2
    dartz: ^0.10.1
    dio: ^4.0.6
    dio_logging_interceptor: ^1.0.1
    email_validator: ^2.1.17
    equatable: ^2.0.3
    event_bus: ^2.0.0
    floor: ^1.2.0
    flutter_bloc: ^8.1.1
    flutter_image_compress: ^1.1.3
    flutter_local_notifications: ^9.7.0
    flutter_profile_picture: ^2.0.0
    flutter_screenutil: ^5.5.3+2
    flutter_secure_storage: ^5.0.2
    get_it: ^7.2.0
    get:
    go_router: ^4.2.7
    google_fonts: ^3.0.1
    http_interceptor: ^1.0.2
    hydrated_bloc: ^8.1.0
    image_picker: ^0.8.6
    image_cropper: ^3.0.1
    infinite_scroll_pagination: ^3.2.0
    injectable: ^1.5.3
    intl: ^0.17.0
    json_annotation: ^4.5.0
    path_provider: ^2.0.11
    permission_handler: ^10.0.0
    retrofit: ^3.0.1+1
    rounded_loading_button: ^2.1.0
    rxdart: ^0.27.5
    shared_preferences: ^2.0.15
    uuid: ^3.0.6
    pull_to_refresh: ^2.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    
    build_runner:
    copy_with_extension_gen: ^4.0.0
    floor_generator: ^1.2.0
    flutter_gen_runner:
    flutter_lints: ^2.0.0
    injectable_generator:
    json_serializable:
    retrofit_generator:

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/images/
        - assets/maps/